// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phdplortjkuclajdkxur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZHBsb3J0amt1Y2xhamRreHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODQ5MDksImV4cCI6MjA2OTQ2MDkwOX0.wiOlYfakFVQFgWm_QATAIwwlzEnIkvpcK01KrRoKvqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});